/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersNewRouteImport } from './routes/_authenticated/customers.new'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedCustomersIdViewRouteImport } from './routes/_authenticated/customers.$id.view'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/_authenticated/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/_authenticated/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/_authenticated/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/_authenticated/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/_authenticated/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/_authenticated/customers/',
    path: '/customers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomersNewRoute =
  AuthenticatedCustomersNewRouteImport.update({
    id: '/_authenticated/customers/new',
    path: '/customers/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/_authenticated/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomersIdViewRoute =
  AuthenticatedCustomersIdViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => AuthenticatedCustomersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/accounts': typeof AuthenticatedAccountsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/hr': typeof AuthenticatedHrRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/': typeof AuthenticatedIndexRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRouteWithChildren
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/customers/$id/view': typeof AuthenticatedCustomersIdViewRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof AuthenticatedAccountsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/hr': typeof AuthenticatedHrRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/': typeof AuthenticatedIndexRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRouteWithChildren
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/customers/$id/view': typeof AuthenticatedCustomersIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRouteWithChildren
  '/_authenticated/customers/new': typeof AuthenticatedCustomersNewRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/customers/$id/view': typeof AuthenticatedCustomersIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/accounts'
    | '/contracts'
    | '/hr'
    | '/projects'
    | '/sales'
    | '/'
    | '/customers/$id'
    | '/customers/new'
    | '/customers/'
    | '/customers/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/contracts'
    | '/hr'
    | '/projects'
    | '/sales'
    | '/'
    | '/customers/$id'
    | '/customers/new'
    | '/customers'
    | '/customers/$id/view'
  id:
    | '__root__'
    | '/_authenticated/accounts'
    | '/_authenticated/contracts'
    | '/_authenticated/hr'
    | '/_authenticated/projects'
    | '/_authenticated/sales'
    | '/_authenticated/'
    | '/_authenticated/customers/$id'
    | '/_authenticated/customers/new'
    | '/_authenticated/customers/'
    | '/_authenticated/customers/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRouteWithChildren
  AuthenticatedCustomersNewRoute: typeof AuthenticatedCustomersNewRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers/new': {
      id: '/_authenticated/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthenticatedCustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers/$id/view': {
      id: '/_authenticated/customers/$id/view'
      path: '/view'
      fullPath: '/customers/$id/view'
      preLoaderRoute: typeof AuthenticatedCustomersIdViewRouteImport
      parentRoute: typeof AuthenticatedCustomersIdRoute
    }
  }
}

interface AuthenticatedCustomersIdRouteChildren {
  AuthenticatedCustomersIdViewRoute: typeof AuthenticatedCustomersIdViewRoute
}

const AuthenticatedCustomersIdRouteChildren: AuthenticatedCustomersIdRouteChildren =
  {
    AuthenticatedCustomersIdViewRoute: AuthenticatedCustomersIdViewRoute,
  }

const AuthenticatedCustomersIdRouteWithChildren =
  AuthenticatedCustomersIdRoute._addFileChildren(
    AuthenticatedCustomersIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRouteWithChildren,
  AuthenticatedCustomersNewRoute: AuthenticatedCustomersNewRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
