/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as HrRouteImport } from './routes/hr'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CustomersIdViewRouteImport } from './routes/customers.$id.view'

const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdViewRoute = CustomersIdViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => CustomersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/contracts': typeof ContractsRoute
  '/hr': typeof HrRoute
  '/projects': typeof ProjectsRoute
  '/sales': typeof SalesRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/customers/$id/view': typeof CustomersIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/contracts': typeof ContractsRoute
  '/hr': typeof HrRoute
  '/projects': typeof ProjectsRoute
  '/sales': typeof SalesRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/customers': typeof CustomersIndexRoute
  '/customers/$id/view': typeof CustomersIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/contracts': typeof ContractsRoute
  '/hr': typeof HrRoute
  '/projects': typeof ProjectsRoute
  '/sales': typeof SalesRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/customers/$id/view': typeof CustomersIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/contracts'
    | '/hr'
    | '/projects'
    | '/sales'
    | '/customers/$id'
    | '/customers/new'
    | '/customers/'
    | '/customers/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/contracts'
    | '/hr'
    | '/projects'
    | '/sales'
    | '/customers/$id'
    | '/customers/new'
    | '/customers'
    | '/customers/$id/view'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/contracts'
    | '/hr'
    | '/projects'
    | '/sales'
    | '/customers/$id'
    | '/customers/new'
    | '/customers/'
    | '/customers/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ContractsRoute: typeof ContractsRoute
  HrRoute: typeof HrRoute
  ProjectsRoute: typeof ProjectsRoute
  SalesRoute: typeof SalesRoute
  CustomersIdRoute: typeof CustomersIdRouteWithChildren
  CustomersNewRoute: typeof CustomersNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/view': {
      id: '/customers/$id/view'
      path: '/view'
      fullPath: '/customers/$id/view'
      preLoaderRoute: typeof CustomersIdViewRouteImport
      parentRoute: typeof CustomersIdRoute
    }
  }
}

interface CustomersIdRouteChildren {
  CustomersIdViewRoute: typeof CustomersIdViewRoute
}

const CustomersIdRouteChildren: CustomersIdRouteChildren = {
  CustomersIdViewRoute: CustomersIdViewRoute,
}

const CustomersIdRouteWithChildren = CustomersIdRoute._addFileChildren(
  CustomersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ContractsRoute: ContractsRoute,
  HrRoute: HrRoute,
  ProjectsRoute: ProjectsRoute,
  SalesRoute: SalesRoute,
  CustomersIdRoute: CustomersIdRouteWithChildren,
  CustomersNewRoute: CustomersNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
